name: David Rowell
favicon: null
layout_spectrum: 0.17279192013666034
typography_spectrum: 0.5528642125427723
title: Online Portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.04924774123355746
  lightness: 0.9513345174491405
  saturation: 0.39360763947479427
  rhythmicContrast: 0.8780889369081706
purpose: []
